import { Service } from "../types";

export const MOCK_SERVICES: Service[] = [
    {
        id: "svc-001",
        serviceCode: "NCWSC-CON-001",
        name: "New Water Connection",
        nameSwahili: "Ombi la Muunganisho Mpya wa Maji",
        department: "Engineering & New Connections",
        description: "Apply for a new potable water supply line to residential or commercial premises within Nairobi's service area. Includes site survey, line installation, and meter fitting.",
        module: "Service Request Management",
        icon: "🚰",
        status: "active",
        sla: { acknowledgementHours: 24, resolutionHours: 72, escalationHours: 48, priority: "high" },
        applicationFeeKES: 2500,
        requiresFieldVisit: true,
        selfServiceEligible: true,
        documentsRequired: ["National ID / Passport", "Proof of property ownership", "Site plan / survey map", "Recent utility bill (plot reference)", "Letter from county government (for subdivisions)"],
        tags: ["connections", "new_service", "engineering"],
        createdAt: "2024-01-10T08:00:00Z",
        updatedAt: "2024-11-01T10:30:00Z",
    },
    {
        id: "svc-002",
        serviceCode: "NCWSC-REC-001",
        name: "Reconnection After Disconnection",
        nameSwahili: "Ombi la Kuunganishwa Tena Baada ya Kukatwa",
        department: "Revenue & Collections",
        description: "Reinstate water supply that was disconnected due to non-payment or violation. Requires outstanding balance settlement and reconnection fee payment before field visit.",
        module: "Service Request Management",
        icon: "🔄",
        status: "active",
        sla: { acknowledgementHours: 4, resolutionHours: 24, escalationHours: 12, priority: "high" },
        applicationFeeKES: 1500,
        requiresFieldVisit: true,
        selfServiceEligible: true,
        documentsRequired: ["Payment receipt for outstanding bill", "Reconnection fee receipt"],
        tags: ["reconnection", "billing", "revenue"],
        createdAt: "2024-01-10T08:00:00Z",
        updatedAt: "2024-10-15T09:00:00Z",
    },
    {
        id: "svc-003",
        serviceCode: "NCWSC-MTR-001",
        name: "Meter Replacement Request",
        nameSwahili: "Ombi la Ubadilishaji wa Mita",
        department: "Metering & Revenue Protection",
        description: "Request replacement of a faulty, aged, or tampered water meter. NCWSC verifies meter condition on-site before approval. Smart AMR meters available for commercial accounts.",
        module: "Meter Data Management",
        icon: "🔢",
        status: "active",
        sla: { acknowledgementHours: 48, resolutionHours: 120, escalationHours: 72, priority: "medium" },
        applicationFeeKES: 0,
        requiresFieldVisit: true,
        selfServiceEligible: true,
        documentsRequired: ["Account number", "Description of fault", "Meter serial number (if visible)"],
        tags: ["meter", "maintenance", "metering"],
        createdAt: "2024-01-10T08:00:00Z",
        updatedAt: "2024-09-20T11:00:00Z",
    },
    {
        id: "svc-004",
        serviceCode: "NCWSC-MTR-002",
        name: "Customer Meter Reading Submission",
        nameSwahili: "Usomaji wa Mita na Mteja",
        department: "Metering & Revenue Protection",
        description: "Submit your own meter reading online to ensure accurate billing. High-resolution photo upload required. Readings are validated against historical consumption patterns.",
        module: "Meter Data Management",
        icon: "📸",
        status: "active",
        sla: { acknowledgementHours: 2, resolutionHours: 4, escalationHours: 24, priority: "low" },
        applicationFeeKES: 0,
        requiresFieldVisit: false,
        selfServiceEligible: true,
        documentsRequired: ["Meter photo (current reading visible)", "Meter serial number"],
        tags: ["meter", "self_service", "reading"],
        createdAt: "2024-01-10T08:00:00Z",
        updatedAt: "2024-11-05T08:00:00Z",
    },
    {
        id: "svc-005",
        serviceCode: "NCWSC-BIL-001",
        name: "Billing Dispute / Query",
        nameSwahili: "Pingamizi la Bili",
        department: "Customer Service & Billing",
        description: "Raise a formal dispute for incorrect billing, estimated readings, or double charges. Our billing team investigates within the SLA period and issues a corrected invoice if needed.",
        module: "Billing Management",
        icon: "📋",
        status: "active",
        sla: { acknowledgementHours: 4, resolutionHours: 48, escalationHours: 24, priority: "medium" },
        applicationFeeKES: 0,
        requiresFieldVisit: false,
        selfServiceEligible: true,
        documentsRequired: ["Bill number", "Description of dispute", "Previous payment receipts (if applicable)"],
        tags: ["billing", "dispute", "customer_service"],
        createdAt: "2024-01-10T08:00:00Z",
        updatedAt: "2024-10-01T14:00:00Z",
    },
    {
        id: "svc-006",
        serviceCode: "NCWSC-FAU-001",
        name: "Pipe Burst / Leak Report",
        nameSwahili: "Ripoti ya Bomba Lililotoboka",
        department: "Network Operations & Maintenance",
        description: "Report a burst pipe, visible leak, or suspicious water flow on public or private infrastructure. GPS location is auto-captured to dispatch the nearest available technician.",
        module: "Fault / Leak Reporting",
        icon: "⚠️",
        status: "active",
        sla: { acknowledgementHours: 1, resolutionHours: 4, escalationHours: 2, priority: "critical" },
        applicationFeeKES: 0,
        requiresFieldVisit: true,
        selfServiceEligible: true,
        documentsRequired: ["GPS location (auto-captured)", "Fault description", "Photo (optional)"],
        tags: ["fault", "emergency", "nrw", "maintenance"],
        createdAt: "2024-01-10T08:00:00Z",
        updatedAt: "2024-11-10T07:00:00Z",
    },
    {
        id: "svc-007",
        serviceCode: "NCWSC-FAU-002",
        name: "Low Water Pressure Complaint",
        nameSwahili: "Malalamiko ya Shinikizo Ndogo la Maji",
        department: "Network Operations & Maintenance",
        description: "Report persistently low water pressure affecting your premises. Operations team will assess network conditions, check pressure zones, and carry out any required balancing.",
        module: "Fault / Leak Reporting",
        icon: "🌊",
        status: "active",
        sla: { acknowledgementHours: 8, resolutionHours: 48, escalationHours: 24, priority: "medium" },
        applicationFeeKES: 0,
        requiresFieldVisit: true,
        selfServiceEligible: true,
        documentsRequired: ["Account number", "Description of issue", "Times when pressure is lowest"],
        tags: ["fault", "pressure", "network"],
        createdAt: "2024-01-10T08:00:00Z",
        updatedAt: "2024-09-15T09:00:00Z",
    },
    {
        id: "svc-008",
        serviceCode: "NCWSC-FAU-003",
        name: "Water Supply Interruption Report",
        nameSwahili: "Ripoti ya Usumbufu wa Ugavi wa Maji",
        department: "Network Operations & Maintenance",
        description: "Report complete absence of water supply exceeding 12 hours. Our control room will cross-reference with scheduled maintenance and escalate if unplanned.",
        module: "Fault / Leak Reporting",
        icon: "🚫",
        status: "active",
        sla: { acknowledgementHours: 2, resolutionHours: 12, escalationHours: 6, priority: "high" },
        applicationFeeKES: 0,
        requiresFieldVisit: false,
        selfServiceEligible: true,
        documentsRequired: ["Account number", "Duration without supply", "Last seen supply date/time"],
        tags: ["fault", "emergency", "supply"],
        createdAt: "2024-01-10T08:00:00Z",
        updatedAt: "2024-11-01T08:00:00Z",
    },
    {
        id: "svc-009",
        serviceCode: "NCWSC-FAU-004",
        name: "Suspected Illegal Connection Report",
        nameSwahili: "Ripoti ya Muunganisho Haramu",
        department: "Revenue Protection & Enforcement",
        description: "Report suspected illegal or unauthorised water tapping, meter bypassing, or meter tampering. All reports are treated confidentially and investigated by the enforcement team.",
        module: "Fault / Leak Reporting",
        icon: "🔍",
        status: "active",
        sla: { acknowledgementHours: 12, resolutionHours: 72, escalationHours: 48, priority: "high" },
        applicationFeeKES: 0,
        requiresFieldVisit: true,
        selfServiceEligible: true,
        documentsRequired: ["Location / plot reference", "Description of suspected activity"],
        tags: ["fault", "nrw", "enforcement", "security"],
        createdAt: "2024-01-10T08:00:00Z",
        updatedAt: "2024-10-20T10:00:00Z",
    },
    {
        id: "svc-010",
        serviceCode: "NCWSC-CON-002",
        name: "Bulk / Tanker Water Supply Request",
        nameSwahili: "Ombi la Ugavi wa Maji kwa Tanki",
        department: "Commercial & Bulk Supply",
        description: "Order water delivery via licensed NCWSC tanker for construction sites, events, or emergency fill of storage tanks. Pricing is per trip based on tanker capacity (5,000–10,000 L).",
        module: "Service Request Management",
        icon: "🚛",
        status: "active",
        sla: { acknowledgementHours: 4, resolutionHours: 24, escalationHours: 12, priority: "medium" },
        applicationFeeKES: 0,
        requiresFieldVisit: false,
        selfServiceEligible: true,
        documentsRequired: ["Delivery address", "Quantity required", "Preferred date/time"],
        tags: ["bulk_supply", "commercial", "tanker"],
        createdAt: "2024-01-10T08:00:00Z",
        updatedAt: "2024-10-10T12:00:00Z",
    },
    {
        id: "svc-011",
        serviceCode: "NCWSC-ACC-001",
        name: "Account Name Change",
        nameSwahili: "Kubadilisha Jina la Akaunti",
        department: "Customer Service",
        description: "Update the registered account holder name due to property transfer, inheritance, marriage, or legal name change. A notarized copy of the supporting legal document is required.",
        module: "User Account Management",
        icon: "👤",
        status: "active",
        sla: { acknowledgementHours: 8, resolutionHours: 72, escalationHours: 48, priority: "low" },
        applicationFeeKES: 500,
        requiresFieldVisit: false,
        selfServiceEligible: true,
        documentsRequired: ["Original account holder ID", "New holder ID", "Transfer/legal document (notarized)"],
        tags: ["account", "customer_service", "administrative"],
        createdAt: "2024-01-10T08:00:00Z",
        updatedAt: "2024-08-01T09:00:00Z",
    },
    {
        id: "svc-012",
        serviceCode: "NCWSC-ACC-002",
        name: "Voluntary Disconnection Request",
        nameSwahili: "Ombi la Kukatwa kwa Hiari",
        department: "Customer Service",
        description: "Request temporary or permanent disconnection of your water supply (e.g. property sale, relocation, extended absence). Settlement of all outstanding bills is required before processing.",
        module: "User Account Management",
        icon: "🔒",
        status: "active",
        sla: { acknowledgementHours: 24, resolutionHours: 48, escalationHours: 36, priority: "low" },
        applicationFeeKES: 0,
        requiresFieldVisit: true,
        selfServiceEligible: true,
        documentsRequired: ["Bill clearance certificate", "Reason for disconnection"],
        tags: ["account", "disconnection", "administrative"],
        createdAt: "2024-01-10T08:00:00Z",
        updatedAt: "2024-09-01T11:00:00Z",
    },
    {
        id: "svc-013",
        serviceCode: "NCWSC-TAR-001",
        name: "Tariff Category Change",
        nameSwahili: "Mabadiliko ya Aina ya Ushuru",
        department: "Revenue & Billing",
        description: "Apply to reclassify your account tariff (e.g. domestic to commercial or vice versa). An NCWSC inspector will verify the premises usage before the change is approved.",
        module: "Billing Management",
        icon: "📊",
        status: "active",
        sla: { acknowledgementHours: 48, resolutionHours: 120, escalationHours: 72, priority: "low" },
        applicationFeeKES: 1000,
        requiresFieldVisit: true,
        selfServiceEligible: true,
        documentsRequired: ["Current account details", "Business registration (for commercial)", "Reason for category change"],
        tags: ["billing", "tariff", "reclassification"],
        createdAt: "2024-01-10T08:00:00Z",
        updatedAt: "2024-07-15T10:00:00Z",
    },
    {
        id: "svc-014",
        serviceCode: "NCWSC-ENV-001",
        name: "Water Quality Complaint",
        nameSwahili: "Malalamiko kuhusu Ubora wa Maji",
        department: "Quality Assurance & Environment",
        description: "Report discoloured, odorous, or suspected contaminated water supply. NCWSC will dispatch a quality officer to collect samples for laboratory analysis within the SLA period.",
        module: "Fault / Leak Reporting",
        icon: "🧪",
        status: "active",
        sla: { acknowledgementHours: 2, resolutionHours: 48, escalationHours: 12, priority: "critical" },
        applicationFeeKES: 0,
        requiresFieldVisit: true,
        selfServiceEligible: true,
        documentsRequired: ["Account number", "Description of quality issue", "Photo (if water is visibly discoloured)"],
        tags: ["quality", "environment", "fault", "health"],
        createdAt: "2024-01-10T08:00:00Z",
        updatedAt: "2024-11-08T08:00:00Z",
    },
    {
        id: "svc-015",
        serviceCode: "NCWSC-CON-003",
        name: "Sewer Connection Application",
        nameSwahili: "Ombi la Muunganisho wa Mfereji wa Taka",
        department: "Sewerage & Wastewater",
        description: "Apply to connect your premises to the Nairobi sewerage network. Includes excavation, lateral line installation, and inspection. Applicable in areas with existing sewer mains.",
        module: "Service Request Management",
        icon: "🔧",
        status: "active",
        sla: { acknowledgementHours: 48, resolutionHours: 168, escalationHours: 96, priority: "medium" },
        applicationFeeKES: 5000,
        requiresFieldVisit: true,
        selfServiceEligible: true,
        documentsRequired: ["Land ownership documents", "Building plan approved by Nairobi City County", "National ID", "Application fee receipt"],
        tags: ["sewerage", "new_service", "engineering"],
        createdAt: "2024-01-10T08:00:00Z",
        updatedAt: "2024-10-05T09:30:00Z",
    },
    {
        id: "svc-016",
        serviceCode: "NCWSC-PAY-001",
        name: "Payment Plan / Instalment Request",
        nameSwahili: "Ombi la Mpango wa Malipo",
        department: "Revenue & Collections",
        description: "Apply for a structured instalment plan to clear a large outstanding water bill. Plans span 3–12 months and require an initial deposit of at least 30% of the total balance.",
        module: "Billing Management",
        icon: "💳",
        status: "active",
        sla: { acknowledgementHours: 24, resolutionHours: 48, escalationHours: 36, priority: "medium" },
        applicationFeeKES: 0,
        requiresFieldVisit: false,
        selfServiceEligible: true,
        documentsRequired: ["Account number", "Outstanding bill details", "Employment / income proof (optional)"],
        tags: ["billing", "payment", "collections"],
        createdAt: "2024-01-10T08:00:00Z",
        updatedAt: "2024-10-25T08:00:00Z",
    },
    {
        id: "svc-017",
        serviceCode: "NCWSC-INS-001",
        name: "Plumbing Inspection Request",
        nameSwahili: "Ombi la Ukaguzi wa Mabomba",
        department: "Engineering & Technical Services",
        description: "Request a certified NCWSC plumbing inspection for new constructions or before finalising property transactions. A formal compliance certificate is issued on passing.",
        module: "Service Request Management",
        icon: "🏗️",
        status: "active",
        sla: { acknowledgementHours: 48, resolutionHours: 120, escalationHours: 72, priority: "low" },
        applicationFeeKES: 3000,
        requiresFieldVisit: true,
        selfServiceEligible: true,
        documentsRequired: ["Building plan", "Property ownership document", "Contractor details"],
        tags: ["inspection", "engineering", "compliance"],
        createdAt: "2024-01-10T08:00:00Z",
        updatedAt: "2024-09-10T10:00:00Z",
    },
    {
        id: "svc-018",
        serviceCode: "NCWSC-CON-004",
        name: "Service Pipe Relocation",
        nameSwahili: "Uhamishaji wa Bomba la Huduma",
        department: "Engineering & New Connections",
        description: "Request relocation of an existing service pipe or meter box due to construction, renovation, or road works. Customer bears the cost of relocation as per the current tariff schedule.",
        module: "Service Request Management",
        icon: "📍",
        status: "active",
        sla: { acknowledgementHours: 48, resolutionHours: 120, escalationHours: 72, priority: "medium" },
        applicationFeeKES: 7500,
        requiresFieldVisit: true,
        selfServiceEligible: true,
        documentsRequired: ["Account number", "Building permit (if under construction)", "Sketch of desired new location"],
        tags: ["connections", "relocation", "engineering"],
        createdAt: "2024-01-10T08:00:00Z",
        updatedAt: "2024-08-20T09:00:00Z",
    },
    {
        id: "svc-019",
        serviceCode: "NCWSC-CONS-001",
        name: "Water Conservation Advisory",
        nameSwahili: "Ushauri wa Uhifadhi wa Maji",
        department: "Environment & Sustainability",
        description: "Book a free water audit consultation for residential or commercial premises. A trained NCWSC conservation officer identifies leaks, inefficiencies, and provides a reduction plan.",
        module: "Analytics & Reporting",
        icon: "🌿",
        status: "active",
        sla: { acknowledgementHours: 48, resolutionHours: 120, escalationHours: 96, priority: "low" },
        applicationFeeKES: 0,
        requiresFieldVisit: true,
        selfServiceEligible: true,
        documentsRequired: ["Account number", "Preferred appointment date"],
        tags: ["conservation", "sustainability", "advisory"],
        createdAt: "2024-01-10T08:00:00Z",
        updatedAt: "2024-11-01T08:00:00Z",
    },
    {
        id: "svc-020",
        serviceCode: "NCWSC-RPT-001",
        name: "Statement of Account Request",
        nameSwahili: "Ombi la Taarifa ya Akaunti",
        department: "Customer Service & Billing",
        description: "Request an official statement of account showing billing history, payments, and outstanding balance for a specified period. Useful for audits, tenders, and lease agreements.",
        module: "Billing Management",
        icon: "📄",
        status: "active",
        sla: { acknowledgementHours: 4, resolutionHours: 24, escalationHours: 12, priority: "low" },
        applicationFeeKES: 200,
        requiresFieldVisit: false,
        selfServiceEligible: true,
        documentsRequired: ["Account number", "Requested date range", "Purpose of statement"],
        tags: ["billing", "documentation", "reporting", "self_service"],
        createdAt: "2024-01-10T08:00:00Z",
        updatedAt: "2024-11-05T09:00:00Z",
    },
];
